builders:
  retrofit_wrapper_generator:
    import: "package:retrofit_wrapper_generator/builder.dart"
    builder_factories: ["retrofitWrapperBuilder"]
    build_extensions: { ".dart": [".wrapper.dart"] }
    auto_apply: dependents
    build_to: source
    # build_to: cache
    # applies_builders: ["source_gen|combining_builder"]