name: retrofit_wrapper_generator
description: retrofit_wrapper generator
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.2.3

dependencies:
  analyzer: ^6.2.0
  build: ^2.4.1
  code_builder: ^4.9.0
  dart_style: ^2.3.4
  dev: ^1.0.0
  retrofit_wrapper:
    git:
      url: https://github.com/ebwood/retrofit_wrapper_tools
      ref: main
      path: retrofit_wrapper
  source_gen: ^1.5.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
